string input for team and org, check if team/org mapping exists

diff --git a/.github/workflows/handle-repository-creation.yml b/.github/workflows/handle-repository-creation.yml
--- a/.github/workflows/handle-repository-creation.yml
+++ b/.github/workflows/handle-repository-creation.yml
@@ -90,9 +90,17 @@ jobs:
       
           # map the team name to the team abbreviation
           team_abbr=$(yq e '.team."${{ steps.issue-values.outputs.team_name }}"' /config/naming-convention.yml)
-          
+          if [[ -z "${team_abbr}" ]]; then
+            echo "Error: No mapping found for team name"
+            exit 1
+          fi
+
           # map the organization name to the organization abbreviation
           org_abbr=$(yq e '.organization."${{ steps.issue-values.outputs.org_name }}"' /config/naming-convention.yml)
+          if [[ -z "${org_abbr}" ]]; then
+            echo "Error: No mapping found for organization name"
+            exit 1
+          fi
       
           final_name="${org_abbr}-${team_abbr}-${{ steps.issue-values.outputs.repo_name }}"
           echo "repo_name=${final_name}" >> "$GITHUB_ENV"
